site_name: BrainSim docs
site_author: GoodAI
repo_url: https://github.com/GoodAI
#theme: mkdocs, bootstrap, cosmo, flatly, spacelab, united, yeti
theme_dir: 'goodai_theme'
pages:
- Intro: 'index.md'
- Model: 'model.md'
- UI: 'ui.md'
- Observers: 'observer.md'
#- ['nodes.md', 'Nodes']
- Guides:
    - How to create a module: 'guides/steps.md'
    - Persitence: 'guides/persistence.md'
    - Discrete QLearning: 'guides/discreteqlearning.md'
- Examples: 'examples.md'
- Changelog: 'changelog.md'
markdown_extensions:
    - fenced_code
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML', 'js/mathjaxhelper.js']
use_directory_urls: false
