site_name: BrainSim docs
site_author: GoodAI
repo_url: https://github.com/GoodAI
#theme: mkdocs, bootstrap, cosmo, flatly, spacelab, united, yeti
theme_dir: 'goodai_theme'
pages:
- Intro: 'index.md'
- Model: 'model.md'
- UI: 'ui.md'
- Observers: 'observer.md'
#- ['nodes.md', 'Nodes']
- Guides:
    - How to create a module: 'guides/steps.md'
    - Persistence: 'guides/persistence.md'
    - Math Operations: 'guides/matrix.md'
    - Neural Network: 'guides/neuralnetwork.md'
    - Discrete Q-Learning: 'guides/discreteqlearning.md'
    - Image Processing: 'guides/improc.md'
    - Restricted Boltzmann Machine: 'guides/rbm.md'

- Examples:
    - Matrix Node: 'examples/matrix.md'
    - Neural Network: 'examples/neuralnetwork.md'
    - Discrete Q-Learning: 'examples/discreteqlearning.md'
    - Image Processing: 'examples/improc.md'
    - Restricted Boltzmann Machine: 'examples/rbm.md'
    - Motor Control: 'examples/motor.md'
    - Vector Symbolic Architecture: 'examples/binding.md'

- Changelog: 'changelog.md'
markdown_extensions:
    - fenced_code
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML', 'js/mathjaxhelper.js']
use_directory_urls: false
