site_name: BrainSim docs
site_author: Dušan Fedorčák, Michal Vlasák
#theme: mkdocs, bootstrap, cosmo, flatly, spacelab, united, yeti
theme_dir: 'goodai_theme'
pages:
- Intro: 'index.md'
- Model: 'model.md'
- Persistence: 'persistence.md'
- UI: 'ui.md'
- Observer: 'observer.md'
#- ['nodes.md', 'Nodes']
- Guides:
    - Step-by-step tutorial: 'guides/steps.md'
- Examples: 'examples.md'
- Changelog: 'changelog.md'
markdown_extensions: 
    - fenced_code
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML', 'js/mathjaxhelper.js']
use_directory_urls: false